### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by Rantahu** [nikodraca/SpotifyWebVisualizer#4]
Hey just a suggestion, but would you consider adding a open source license. I would love to work on this project and use it, but there's no open source license.

Consider using a apache or a LGPL licence.
Here's a good article on which licenses to choose.

https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/

**Comment by nikodraca** [comment]
Hi,

That sounds like a great idea, I'd love to have more people working on this! Will do this right away.
